### ISSUE TITLE
Problem with the retrieving results, when some of the results contain empty full text field

### ISSUE THREAD

**Issue by beatrycze-volk** [dbmdz/solr-ocrhighlighting#200]
Hallo,

we have encountered problem with the retrieving results, when some of the results contain empty full text field. Some of our search queries contain OR condition. It is used for querying of documents with certain phrase in full text or their parent documents which have empty strings as content of full text field.

Log from SOLR server:
```
java.lang.RuntimeException: Could not determine OCR format for sample ''
	at de.digitalcollections.solrocr.lucene.OcrHighlighter.lambda$getFormat$6(OcrHighlighter.java:503)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at de.digitalcollections.solrocr.lucene.OcrHighlighter.getFormat(OcrHighlighter.java:501)
	at de.digitalcollections.solrocr.lucene.OcrHighlighter.highlightOcrFields(OcrHighlighter.java:346)
	at de.digitalcollections.solrocr.solr.SolrOcrHighlighter.doHighlighting(SolrOcrHighlighter.java:73)
	at de.digitalcollections.solrocr.solr.OcrHighlightComponent.process(OcrHighlightComponent.java:121)
```

Is there a possibility for error handling when full text contains empty string? Maybe only warning message instead of throwing the error which makes unable to parse the documents which actually contain the full text?

Best regards!

**Comment by albig** [comment]
@jbaiter, your patch solves our issue in https://github.com/kitodo/kitodo-presentation/pull/587. Thank you!

@beatrycze-volk, what do you think?

**Comment by beatrycze-volk** [comment]
@albig @jbaiter First, thanks for such a fast reaction! 

I will compile it today with those changes and test it to make sure that everything works for us.
