### ISSUE TITLE
Setup  with SOLR 9.5 - Access denied

### ISSUE THREAD

**Issue by M3ssman** [dbmdz/solr-ocrhighlighting#419]
Dear jbaiter,

I've tried to install a more recent installation using SOLR 9.5 with V 0.8.4 of the solr-ocrhighlighting plugin but failed.

Document filepointers do point to real files on disc, but each time SOLR complains long about lack of permissions like this

```
2024-04-22 13:11:49.704[WARN ][fulltext_ocr] o.a.s.s.SolrDocumentFetcher Field [ocr_text_std_tokenizer] found in index, but not defined in schema.
2024-04-22 13:11:49.704[WARN ][fulltext_ocr] o.a.s.s.SolrDocumentFetcher Field [ocr_text_withespace_tokenizer] found in index, but not defined in schema.
2024-04-22 13:11:49.722[ERROR][fulltext_ocr] o.a.s.h.RequestHandlerBase Server exception => java.security.AccessControlException: access denied ("java.io.FilePermission" "/opt/dspace/repo/assetstoreOcr/11/93/37/11933705232853397065404800290407426360" "read")
	at java.base/java.security.AccessControlContext.checkPermission(Unknown Source)
java.security.AccessControlException: access denied ("java.io.FilePermission" "/opt/dspace/repo/assetstoreOcr/11/93/37/11933705232853397065404800290407426360" "read")
	at java.base/java.security.AccessControlContext.checkPermission(Unknown Source) ~[?:?]
	at java.base/java.security.AccessController.checkPermission(Unknown Source) ~[?:?]
	at java.base/java.lang.SecurityManager.checkPermission(Unknown Source) ~[?:?]
	at java.base/java.lang.SecurityManager.checkRead(Unknown Source) ~[?:?]
	at java.base/java.io.File.exists(Unknown Source) ~[?:?]
	at com.github.dbmdz.solrocr.model.SourcePointer$FileSource.<init>(SourcePointer.java:26) ~[?:?]
	at com.github.dbmdz.solrocr.model.SourcePointer$FileSource.parse(SourcePointer.java:52) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at com.github.dbmdz.solrocr.model.SourcePointer.parse(SourcePointer.java:131) ~[?:?]
	at solrocr.OcrHighlighter.loadOcrFieldValues(OcrHighlighter.java:531) ~[?:?]
	at solrocr.OcrHighlighter.highlightOcrFields(OcrHighlighter.java:361) ~[?:?]
	at com.github.dbmdz.solrocr.solr.SolrOcrHighlighter.doHighlighting(SolrOcrHighlighter.java:78) ~[?:?]
	at solrocr.OcrHighlightComponent.process(OcrHighlightComponent.java:124) ~[?:?]
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:467) ~[?:?]
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:226) ~[?:?]
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2884) ~[?:?]
	at org.apache.solr.servlet.HttpSolrCall.executeCoreRequest(HttpSolrCall.java:875) ~[?:?]
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:561) ~[?:?]
	at org.apache.solr.servlet.SolrDispatchFilter.dispatch(SolrDispatchFilter.java:262) ~[?:?]
	at org.apache.solr.servlet.SolrDispatchFilter.lambda$doFilter$0(SolrDispatchFilter.java:219) ~[?:?]
	at org.apache.solr.servlet.ServletUtils.traceHttpRequestExecution2(ServletUtils.java:249) ~[?:?]
	at org.apache.solr.servlet.ServletUtils.rateLimitRequest(ServletUtils.java:215) ~[?:?]
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:213) ~[?:?]
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:195) ~[?:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210) ~[jetty-servlet-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) ~[jetty-servlet-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598) ~[jetty-security-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[jetty-servlet-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:228) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:301) ~[jetty-rewrite-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287) ~[jetty-server-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[jetty-io-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) ~[jetty-util-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) ~[jetty-util-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) ~[jetty-util-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193) ~[jetty-util-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) ~[jetty-util-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) ~[jetty-util-10.0.19.jar:10.0.19]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) ~[jetty-util-10.0.19.jar:10.0.19]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
2024-04-22 13:11:49.723[INFO ][fulltext_ocr] o.a.s.c.S.Request webapp=/solr path=/select params={hl.snippets=100&hl.weightMatches=true&q=ocr_text:(afghan)&hl=true&hl.ocr.absoluteHighlights=true&fq=id:25f9198e-7a8e-4e05-8d9a-a4b9117bfe25&hl.fl=ocr_text&hl.ocr.fl=ocr_text&wt=javabin&version=2} hits=1 status=500 QTime=92
2024-04-22 13:11:49.727[ERROR][fulltext_ocr] o.a.s.s.HttpSolrCall 500 Exception => java.security.AccessControlException: access denied ("java.io.FilePermission" "/opt/dspace/repo/assetstoreOcr/11/93/37/11933705232853397065404800290407426360" "read")
```
I could jump into the running container and access the file with path from above, but SOLR/Jetty refuse to read it.

Example documents look like this with `ocr_text` having a several files belonging to this document

```
{
      "id":"25f9198e-7a8e-4e05-8d9a-a4b9117bfe25",
      "ocr_text":"/opt/dspace/repo/assetstoreOcr/11/93/37/11933705232853397065404800290407426360+/opt/dspace/repo/assetstoreOcr/14/53/26/145326648937407164716110532093786368169+/opt/dspace/repo/assetstoreOcr/11/02/83/110283322321308371639627208588475772565+/opt/dspace/repo/assetstoreOcr/38/90/07/38900747166155174962715622660588338976+/opt/dspace/repo/assetstoreOcr/12/33/55/123355119720846883271418143910331135557+/opt/dspace/repo/assetstoreOcr/11/64/80/116480412948597037361156463130025332374",
      "location":["m4c9fee30-5169-433a-a481-26486605a6d0","m0bdf3be9-fd93-426f-adb5-50a2c5469a95","ldadb5dab-0674-462b-b47d-a7dda606555c"],
      "location.comm":["4c9fee30-5169-433a-a481-26486605a6d0","0bdf3be9-fd93-426f-adb5-50a2c5469a95"],
      "location.coll":["dadb5dab-0674-462b-b47d-a7dda606555c"]
    }
```

If I understand correctly, SOLR changed starting von V 9.0 the way data is accessed if outside `SOLR_HOME`.
Did you encounter problems concerning that? 
If not, do you mind sharing information how you store and access the actual index data in some SOLR-core and on the other hand the referenced files on disc?

I've tried to alter the `allowPaths` property in `solr.xml` , which in turn gets mapped into the SOLR 9.5 container, but didnt' have any success yet.

**Comment by jbaiter** [comment]
You need to disable the security manager that locks down the file system API:
https://dbmdz.github.io/solr-ocrhighlighting/wip/indexing/

**Comment by M3ssman** [comment]
Thank you very much! With this I was able to access the files, but I will do some more tests.

Still, I wonder why the `allowPaths` Property didn't do any good, since as user I expected it to handle cases like this.

**Comment by M3ssman** [comment]
I installed the recent setup considering your setup note about security management and it also worked well.
Sorry for the inconvenience.
Feel free to close this issue.

**Comment by jbaiter** [comment]
No inconvenience at all, thank you for the suggestion with `allowPaths`, I'll see if I can't get that working, that would definitely be preferable to disabling the security manager altogether, which can be a dealbreaker in some deployment scenarios.
