### ISSUE TITLE
NoSuchMethodError in OcrFieldHighlighter with Solr 9.7

### ISSUE THREAD

**Issue by thomaslow** [dbmdz/solr-ocrhighlighting#457]
Hello DBMDZ-Team,

there is an incompatibility with the recently released Solr 9.7. Version 9.7 depends on Lucene 9.11.1, which changed the constructor of [FieldHighlighter](https://lucene.apache.org/core/9_11_1/highlighter/org/apache/lucene/search/uhighlight/FieldHighlighter.html) , which doesn't match [OcrFieldHighlighter](https://github.com/dbmdz/solr-ocrhighlighting/blob/ced16ef33af71fc4c024bbf6f42cfa4ca5bd9098/src/main/java/com/github/dbmdz/solrocr/lucene/OcrFieldHighlighter.java#L48-L53) any more.

```
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422326000+02:00 Caused by: java.lang.NoSuchMethodError: 'void org.apache.lucene.search.uhighlight.FieldHighlighter.<init>(java.lang.String, org.apache.lucene.search.uhighlight.FieldOffsetStrategy, java.text.BreakIterator, org.apache.lucene.search.uhighlight.PassageScorer, int, int, org.apache.lucene.search.uhighlight.PassageFormatter)'
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422349000+02:00    at com.github.dbmdz.solrocr.lucene.OcrFieldHighlighter.<init>(OcrFieldHighlighter.java:54) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422374000+02:00    at solrocr.OcrHighlighter.getOcrFieldHighlighter(OcrHighlighter.java:678) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422422000+02:00    at solrocr.OcrHighlighter.highlightOcrFields(OcrHighlighter.java:343) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422454000+02:00    at com.github.dbmdz.solrocr.solr.SolrOcrHighlighter.doHighlighting(SolrOcrHighlighter.java:122) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422494000+02:00    at solrocr.OcrHighlightComponent.process(OcrHighlightComponent.java:134) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422526000+02:00    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:456) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422549000+02:00    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:226) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422581000+02:00    at org.apache.solr.core.SolrCore.execute(SolrCore.java:2880) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422602000+02:00    at org.apache.solr.servlet.HttpSolrCall.executeCoreRequest(HttpSolrCall.java:890) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422626000+02:00    at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:576) ~[?:?]
kitodo_presentation_devel_solr_1 2024-09-11T10:42:09.422647000+02:00    ... 47 more
```

### Steps to reproduce the behavior

Run [kitodo/kitodo-presentation](https://github.com/kitodo/kitodo-presentation/) functional tests with Solr 9.7 and `solr-ocrhighlighting-0.9.0.jar`.

The issue does not occur with Solr 9.6.

Cheers,
Thomas

**Comment by jbaiter** [comment]
Thanks for reporting, I'll start work on Solr 9.7 compatibility soon, likely not before October 1st though, I'm on vacation for the next two weeks.

**Comment by jbaiter** [comment]
Latest release 0.9.1 with support for Solr 9.7 was just released, please give it a try!

**Comment by thomaslow** [comment]
Thank you for your quick response and the update release. Your changes seem to work, see https://github.com/kitodo/kitodo-presentation/pull/1335. Have a nice vacation!
